### Numpy

- np.array() 사용 

In [2]:
import numpy as np 
myList = [1,2,3,4]
print(type(myList))

arr = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4], dtype=float)

print(arr)
print(arr2)
print(type(arr))

<class 'list'>
[1 2 3 4]
[1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [6]:
# 리스트로부터 생성하기 
myList1 = [1,2,3,4]
myList2 = [[1,2,3,4],
            [5,6,7,8]]

arr1 = np.array(myList1)
arr2 = np.array(myList2)

# ndarray의 크기, 차원 확인
print(arr1.shape) # 4행 ndarray, 행만 존재, 열은 x 
print(arr2.shape) # 2행 4열 ndarray


(4,)
(2, 4)


### array에서의 data 타입이 섞인 경우 

In [8]:
# int와 flaot 타입이 섞인 경우
arr1 = np.array([1,2,3,4.923])
print(arr1)

arr2 = np.array([1,2,3,4.923], dtype = int)
print(arr2)

[1.    2.    3.    4.923]
[1 2 3 4]


In [11]:
# int, float, str이 섞인 경우
arr = np.array([1,2,3, 1.23, 2.34, 5.61, 'a','b','c'])
print(arr)
print(type(arr))

['1' '2' '3' '1.23' '2.34' '5.61' 'a' 'b' 'c']
<class 'numpy.ndarray'>


### 슬라이싱 (Slicing)

In [16]:
arr1 = np.array([0, 1,2,3,4,5,6,7,8,9])
print(arr1.shape)
print(arr1[0])
print(arr1[9])
print(arr1[-1])

(10,)
0
9
9


In [23]:
# 2차원 ndarray 
arr2 = np.array([[1,2,3,4],
                [3,4,5,6],
                [7,8,9,0]])

print(arr2)
print(arr2.shape)
print(arr2[1])

[[1 2 3 4]
 [3 4 5 6]
 [7 8 9 0]]
(3, 4)
[3 4 5 6]


### 범위 색인
1. 1차원 

In [24]:
arr = np.array([0,1,2,3,4,5,7,8,9])

print(arr[5:])  # 5부터 마지막까지 
print(arr[:5])  # 처음부터 4까지 
print(arr[1:5]) # 1부터 4까지 
print(arr[:-1]) # 처음부터 마지막 전까지 

[5 7 8 9]
[0 1 2 3 4]
[1 2 3 4]
[0 1 2 3 4 5 7 8]


2. 2차원

In [27]:
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

print(arr2[0, :]) # row를 모두 가져오는 경우 
print(arr2[:, 0]) # col을 모두 가져오는 경우 
print(arr2[0, :].shape)

[1 2 3 4]
[1 5 9]
(4,)


3. Fancy 인덱싱
- fancy 인덱싱은 범위가 아닌 특정 index의 집합의 값을 선택하여 추출하고 싶을 때 사용 

In [28]:
# 1차원 
arr = np.array([10, 23, 2, 7, 30, 90, 2])
idx = [3, 4, 2]
print(arr[idx])

[ 7 30  2]


In [30]:
# 2차원 
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr2[[0, 2], : ]) # 0행과 2행을 가져옴 

[[ 1  2  3  4]
 [ 9 10 11 12]]


### Boolean 인덱싱 
- 조건 필터링을 통하여 Bollean 값을 이용한 색인 

In [31]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [34]:
# True와 Flase 값으로 색인 
myTrueFlase = [True, False, True]
print(arr1[myTrueFlase]) 

# err 뜨는 이유 : 색인 리스트는 3개인데 ndarray는 그 이상의 개수라서 

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 3

In [38]:
# 조건 필터 
arr1 = np.array([1,2,3,4,5,6,7])
print(arr1 > 3)

arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

print(arr2[arr2 > 3]) # 1차원으로 변경된다.
print(arr2[arr2 > 3].shape)

[False False False  True  True  True  True]
[ 4  5  6  7  8  9 10 11 12]
(9,)


### arange 
1. 순서대로 리스트에 값을 생성

In [40]:
arr = np.array([1,2,3,4,5,6,8,9, 10])
print(arr) 

# arange(start, stop, step)
arr = np.arange(1,11) 
print(arr)

[ 1  2  3  4  5  6  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [41]:
def myGen(start=1, stop=10,step=1):
    myList=[]

    for i in range(start,stop,step):
        myList.append(i)
    
    return myList

result = myGen(stop=5, start=2)
result

[2, 3, 4]

### 정렬
1. 행 정렬

In [45]:
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

arr2.sort(axis=0)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## array의 브로드캐스팅 

In [ ]:
a = np.array([[1,2,3], 
            [2,3,4]])

b = np.array([[1], [2]])