In [75]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
rank_2_tensor = tf.constant([
    [10, 7],
    [3, 4]
])

In [3]:
# 각 행의 마지막 열의 값을 가져오기
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [7]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]

# 파이썬에서는 ... 은 모든 것을 의미합니다. rank2_tensor에 존재하는 모든 것

In [5]:
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]])>)

In [6]:
rank_2_tensor.ndim, rank_3_tensor.ndim

(2, 3)

In [8]:
rank_3_tensor = rank_2_tensor[tf.newaxis, ...]

In [9]:
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
 array([[[10,  7],
         [ 3,  4]]])>)

In [10]:
rank_2_tensor.ndim, rank_3_tensor.ndim

(2, 3)

In [11]:
tf.expand_dims(rank_2_tensor, axis=-1) # -1의 의미는 파이썬는 마지막이라는 뜻

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [14]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

In [15]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]])>

In [16]:
# tensor 가지고 놀아보기!
# 사칙연산 + - *

[Tensorflow의 math API](https://www.tensorflow.org/api_docs/python/tf/math/)

In [18]:
tensor = tf.constant([
    [10, 7], 
    [3, 4]
])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [19]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [20]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [22]:
tensor_plus_10 = tensor + 10
tensor_plus_10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [23]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [24]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [28]:
tensor / 5

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 1.4],
       [0.6, 0.8]])>

In [25]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [26]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [27]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [30]:
tf.divide(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 1.4],
       [0.6, 0.8]])>

In [32]:
# 머신 러닝 알고리즘에서 가장 많이 사용하는 연산 중에 하나 행렬 연산 (Matrix multiplication)
# Tensorflow에서는 tf.matmul() 메소드로 matrix multiplication을 구현해 놓았습니다.

[참고](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

In [33]:
# matrix multiplication를 실행할 때 꼭 기억해야 할 것 2개가 있습니다.

1. 각 행렬을 multiplication을 할 때 안에 있는 차원은 같아야 한다.

   (3, 5) @ (3, 5) : 행렬 연산이 안 됨

   (5, 3) @ (3, 5) : 행렬 연산이 가능

   (3, 5) @ (5, 3) : 행렬 연산이 가능

2. 행렬 연산의 결과의 행렬의 크기는 바깥의 차원와 같다.

   (5, 3) @ (3, 5) -> (5, 5)
   
   (3, 5) @ (5, 3) -> (3, 3)

@ : 파이썬에서 matrix multiplication을 의미

In [34]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [35]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [36]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [37]:
X = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

Y = tf.constant([
    [7, 8],
    [9, 10],
    [11, 12]
])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [38]:
X @ Y

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,2] 0 0 [Op:MatMul]

In [39]:
# X, Y는 현재 shape가 (3, 2)!
X.shape, Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [40]:
# 위의 경우에 matrix multiplication을 하려면
# 1. X의 shape를 (2, 3)로 바꾸는 경우   (2, 3) @ (3, 2)
# 2. Y의 shape를 (2, 3)로 바꾸는 경우   (3, 2) @ (2, 3)

In [41]:
# tf.reshape() : 텐서의 shape를 우리가 정의한 shape로 변경해 주는 메서드
# tf.transpose() : 주어진 행렬의 행과 열을 바꾸어 주는 메서드

In [44]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [45]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [46]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [47]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [48]:
tf.transpose(X) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [49]:
tf.matmul(a=X, b=Y, transpose_a = True, transpose_b = False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [50]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [51]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [52]:
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [53]:
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [54]:
Y, tf.reshape(Y, (2, 3)), tf.transpose(Y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]])>)

In [58]:
# 16-비트 floating precision vs. 32-비트 floating precision
# 낮은 precision이 모바일 장치와 같은 컴퓨팅이나 메모리가 작을 경우에 유용

In [65]:
B = tf.constant([
    [1.7, 7.4]
])

C = tf.constant([
    [1, 7]
])

B, C

(<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1.7, 7.4]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 7]])>)

In [66]:
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(1, 2), dtype=float16, numpy=array([[1.7, 7.4]], dtype=float16)>

In [68]:
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 7.]], dtype=float32)>

In [69]:
# 절대값 구하기
D = tf.constant([
    [-7, -10]
])
D

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ -7, -10]])>

In [70]:
tf.abs(D)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ 7, 10]])>

In [71]:
# aggregation 함수 사용하기 min, max, mean, sum)
# tf.reduce_min()
# tf.reduce_max()
# tf.reduce_mean()
# tf.reduce_sum()


In [78]:
np.random.randint(low = 0, high = 100, size =50)

array([64, 38, 27, 71, 51, 75, 86, 58, 52, 13, 36, 32, 67,  3, 19, 77, 56,
       67, 73, 39,  1, 22, 87, 75,  3, 97, 51, 99, 83, 38, 73, 75, 52, 19,
       87, 76, 44, 21, 92, 66, 98, 77, 82, 69, 74, 55,  3,  1, 10, 91])

In [79]:
type(np.random.randint(low = 0, high = 100, size =50))

numpy.ndarray

In [80]:

E = tf.constant(np.random.randint(low = 0, high = 100, size =50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([98,  9, 77, 16, 68,  1, 82, 78, 39, 89, 18,  1, 96, 46, 23, 11, 26,
       74, 60, 10, 11, 20, 42, 45, 34, 56, 25, 31, 92,  5, 26,  2, 75, 80,
       10,  5, 30,  8, 36,  2, 68, 30, 49,  1, 21, 82, 54, 32, 30, 84])>

In [81]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [83]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [84]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=40>

In [85]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2008>

In [91]:
F = tf.constant(np.random.random(50)) # 0 ~ 1사이의 값을 랜덤으로 만들어 준다.
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.34426976, 0.63326289, 0.76392092, 0.90645537, 0.26107193,
       0.27672357, 0.79165827, 0.56834435, 0.95350512, 0.8645175 ,
       0.2396003 , 0.73106019, 0.11019421, 0.65229451, 0.41677982,
       0.72324155, 0.82579866, 0.21420545, 0.60787874, 0.48463318,
       0.36672061, 0.7964879 , 0.94254596, 0.77667933, 0.78979344,
       0.46688097, 0.20190866, 0.61680524, 0.49137825, 0.20251843,
       0.13537759, 0.64396178, 0.64393058, 0.36800123, 0.08914054,
       0.52504278, 0.40291183, 0.92732438, 0.54336742, 0.01251257,
       0.60774282, 0.59351953, 0.53953196, 0.85997716, 0.59357955,
       0.6787775 , 0.06913045, 0.86577257, 0.30938146, 0.10383641])>

In [92]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [93]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=39>

In [103]:
print("F에서의 최대값의 위치 : ", tf.argmax(F).numpy())
print("F에서의 최대값 :", tf.reduce_max(F).numpy())
print("F에서의 최대값의 위치를 인덱스로 해서 찾은 최대값 : ", F[tf.argmax(F)].numpy())
print("F에서의 최소값의 위치 : ", tf.argmin(F).numpy())
print("F에서의 최소값 :", tf.reduce_min(F).numpy() )
print("F에서의 최대값의 위치를 인덱스로 해서 찾은 최대값과 F에서의 최대값은 같을까요? ", F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy())

F에서의 최대값의 위치 :  8
F에서의 최대값 : 0.9535051199235312
F에서의 최대값의 위치를 인덱스로 해서 찾은 최대값 :  0.9535051199235312
F에서의 최소값의 위치 :  39
F에서의 최소값 : 0.012512572732988558
F에서의 최대값의 위치를 인덱스로 해서 찾은 최대값과 F에서의 최대값은 같을까요?  True


In [109]:
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 2, 25))
G.shape, G.ndim, G

(TensorShape([1, 1, 1, 2, 25]),
 5,
 <tf.Tensor: shape=(1, 1, 1, 2, 25), dtype=int32, numpy=
 array([[[[[61, 94, 27,  3, 55,  1, 78, 86, 79,  5, 70, 80, 60, 85, 87,
            24, 78, 44, 36, 86, 57,  2, 24, 10, 27],
           [87,  1, 22, 87, 46, 64,  8,  8, 20, 26, 51, 54, 98, 46, 92,
             7, 93, 44, 93, 24, 77,  9, 39, 19, 46]]]]])>)

In [110]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim, G_squeezed

(TensorShape([2, 25]),
 2,
 <tf.Tensor: shape=(2, 25), dtype=int32, numpy=
 array([[61, 94, 27,  3, 55,  1, 78, 86, 79,  5, 70, 80, 60, 85, 87, 24,
         78, 44, 36, 86, 57,  2, 24, 10, 27],
        [87,  1, 22, 87, 46, 64,  8,  8, 20, 26, 51, 54, 98, 46, 92,  7,
         93, 44, 93, 24, 77,  9, 39, 19, 46]])>)

In [113]:
# one-hot encoding
list_example = [0, 1, 2, 3]

tf.one_hot(list_example, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [114]:
tf.one_hot(list_example, depth=4, on_value="On", off_value="Off")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'On', b'Off', b'Off', b'Off'],
       [b'Off', b'On', b'Off', b'Off'],
       [b'Off', b'Off', b'On', b'Off'],
       [b'Off', b'Off', b'Off', b'On']], dtype=object)>