## autograd_study.ipynb


In [1]:
import torch

In [2]:
x = torch.tensor([5], dtype = torch.float32, requires_grad= True)
y = torch.tensor([6], dtype = torch.float32, requires_grad= True)

In [3]:
x, y

(tensor([5.], requires_grad=True), tensor([6.], requires_grad=True))

In [4]:
z = ( (x**2) * y ) + ( x * y )

In [5]:
z

tensor([180.], grad_fn=<AddBackward0>)

In [6]:
total = torch.sum(z)

In [7]:
total

tensor(180., grad_fn=<SumBackward0>)

In [8]:
total.backward()

In [9]:
print(x.grad)

tensor([66.])


In [10]:
print(y.grad)

tensor([30.])


In [11]:
x = torch.randn(10)
x

tensor([ 1.0397,  0.6314,  1.1401,  1.0124,  1.2789,  0.3531,  0.8706,  0.3758,
        -1.1718, -0.3062])

In [24]:
y = 1.8 * x + 32  # y = wx + b
y

tensor([33.8714, 33.1364, 34.0522, 33.8223, 34.3020, 32.6356, 33.5672, 32.6764,
        29.8908, 31.4488])

In [25]:
w = torch.ones(1, requires_grad = True)
w

tensor([1.], requires_grad=True)

In [26]:
b = torch.ones(1, requires_grad = True)
b


tensor([1.], requires_grad=True)

In [27]:
y_hat = w * x + b  # hat은 predicted value
y_hat

tensor([ 2.0397,  1.6314,  2.1401,  2.0124,  2.2789,  1.3531,  1.8706,  1.3758,
        -0.1718,  0.6938], grad_fn=<AddBackward0>)

In [28]:
loss = torch.sum( (y_hat - y)**2 )

In [29]:
loss

tensor(9874.1865, grad_fn=<SumBackward0>)

In [30]:
loss.backward()

In [31]:
print(w.grad, b.grad)

tensor([-336.5777]) tensor([-628.3584])


In [23]:
w, w.grad

(tensor([1.], requires_grad=True), tensor([-336.5777]))

In [35]:
x = torch.randint(-100, 100, (100, ), dtype = torch.float32)
x

tensor([-53.,  86.,  -2.,  87.,  47., -26.,  73.,  33.,  69.,  56., -48., -65.,
         51., -40.,  41., -59., -35., -54., -32., -93.,  -1., -40.,  69., -25.,
         55., -78.,  26., -91.,  78., -72.,  -3., -44., -50., -35.,  46.,  73.,
         24., -90., -30., -11., -73.,  51., -60.,  73.,  18.,  91.,   9.,  94.,
         17.,  48., -56., -69.,  92.,  50.,   6., -76.,  60., -53., -41.,  51.,
         39., -16.,  49.,  10.,  42.,  56., -84., -17.,  19.,  40.,  37., -83.,
         97.,  19.,  -3., -62., -90.,  65., -24., -96.,  34.,  47.,  59., -98.,
        -74., -10., -63., -16., -24., -24.,  50.,  38., -11.,   0.,  29.,  44.,
        -64.,  70., -29., -90.])

In [36]:
y = (1.8 * x) + 32
y

tensor([ -63.4000,  186.8000,   28.4000,  188.6000,  116.6000,  -14.8000,
         163.4000,   91.4000,  156.2000,  132.8000,  -54.4000,  -85.0000,
         123.8000,  -40.0000,  105.8000,  -74.2000,  -31.0000,  -65.2000,
         -25.6000, -135.4000,   30.2000,  -40.0000,  156.2000,  -13.0000,
         131.0000, -108.4000,   78.8000, -131.8000,  172.4000,  -97.6000,
          26.6000,  -47.2000,  -58.0000,  -31.0000,  114.8000,  163.4000,
          75.2000, -130.0000,  -22.0000,   12.2000,  -99.4000,  123.8000,
         -76.0000,  163.4000,   64.4000,  195.8000,   48.2000,  201.2000,
          62.6000,  118.4000,  -68.8000,  -92.2000,  197.6000,  122.0000,
          42.8000, -104.8000,  140.0000,  -63.4000,  -41.8000,  123.8000,
         102.2000,    3.2000,  120.2000,   50.0000,  107.6000,  132.8000,
        -119.2000,    1.4000,   66.2000,  104.0000,   98.6000, -117.4000,
         206.6000,   66.2000,   26.6000,  -79.6000, -130.0000,  149.0000,
         -11.2000, -140.8000,   93.200

In [39]:
w = torch.ones(1, requires_grad= True)
b = torch.ones(1, requires_grad= True)
y_hat = ( w*x ) + b # predict value
y_hat

tensor([-52.,  87.,  -1.,  88.,  48., -25.,  74.,  34.,  70.,  57., -47., -64.,
         52., -39.,  42., -58., -34., -53., -31., -92.,   0., -39.,  70., -24.,
         56., -77.,  27., -90.,  79., -71.,  -2., -43., -49., -34.,  47.,  74.,
         25., -89., -29., -10., -72.,  52., -59.,  74.,  19.,  92.,  10.,  95.,
         18.,  49., -55., -68.,  93.,  51.,   7., -75.,  61., -52., -40.,  52.,
         40., -15.,  50.,  11.,  43.,  57., -83., -16.,  20.,  41.,  38., -82.,
         98.,  20.,  -2., -61., -89.,  66., -23., -95.,  35.,  48.,  60., -97.,
        -73.,  -9., -62., -15., -23., -23.,  51.,  39., -10.,   1.,  30.,  45.,
        -63.,  71., -28., -89.], grad_fn=<AddBackward0>)

In [40]:
epochs = 100000
lr = 0.000001

In [42]:
for i in range(epochs):
    loss = torch.sum( (y_hat - y) ** 2 )
    loss.backward()
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad

        w.grad.zero_()
        b.grad.zero_()

    y_hat = ( w*x ) + b

print(w.item(), b.item())

1.7999989986419678 31.99523162841797


In [49]:
x = torch.tensor([5], dtype = torch.float32, requires_grad=True)
y = torch.tensor([6], dtype = torch.float32, requires_grad=True)
print(x, y)

tensor([5.], requires_grad=True) tensor([6.], requires_grad=True)


In [50]:
z = ( (x**2) * y ) + ( x*y )
print(z)

tensor([180.], grad_fn=<AddBackward0>)


In [51]:
z.backward()

In [52]:
x.grad

tensor([66.])

In [53]:
y.grad

tensor([30.])