## neural_network_study.ipynb

In [1]:
import torch
import torch.nn as nn

In [3]:
n_in, n_h, n_out, batch_size = 10, 5, 1, 10

In [4]:
x = torch.randn(batch_size, n_in)
y = torch.tensor([ [1.], [1.], [0.], [1.], [0.], [1.], [0.], [1.], [1.], [0.] ])
x, y

(tensor([[-1.3882,  0.2852,  1.2394,  0.5345, -0.6625,  0.2691, -0.2566,  0.2842,
           0.3016, -0.2141],
         [-0.3795, -0.9243, -2.1069,  0.0254, -1.0579,  0.6431, -0.4024,  0.7362,
          -0.3545,  0.5981],
         [-1.7640, -0.3340, -0.6902,  0.0152,  0.4122,  1.4090, -0.7125, -0.4611,
          -1.2843, -2.0920],
         [ 0.4007, -0.1869,  0.6708,  0.7287, -0.6053,  0.9482, -0.8358,  1.3376,
          -0.5377, -1.1441],
         [-2.3333,  1.1642,  0.0454, -0.4109,  0.9035, -1.2355, -0.0835, -1.2553,
          -0.9208, -0.4069],
         [-0.5793, -0.0824, -1.7324,  0.8250,  0.9503, -1.5946,  0.6201, -1.5958,
          -0.3042, -0.9528],
         [-2.5500, -1.6139, -0.7529,  0.1285, -1.3814, -0.4257,  0.8806, -0.1410,
           0.1853, -0.2760],
         [ 0.7796,  0.6501,  0.6738, -2.3371, -0.6655, -1.1168,  0.6382, -1.6351,
          -0.2606, -0.7088],
         [-0.9767,  1.2501,  0.1272, -0.4378,  0.8377, -0.1693,  0.1710,  0.0587,
          -0.4066,  1.1220],
 

In [5]:
model = nn.Sequential(
    nn.Linear(n_in, n_h),
    nn.ReLU(),
    nn.Linear(n_h, n_out),
    nn.Sigmoid()
)

In [6]:
loss_func = nn.MSELoss()

In [7]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [11]:
for i in range(2500):
    y_pred = model(x)
    loss = loss_func(y_pred, y)

    print("epoch : ", (i + 1), " loss : ", loss.item())
    loss.backward() # 역전파 적용

    optimizer.step() # 모든 파라미터 최신화

    optimizer.zero_grad()

09809494
epoch :  2039  loss :  0.05477767437696457
epoch :  2040  loss :  0.05473340302705765
epoch :  2041  loss :  0.054682422429323196
epoch :  2042  loss :  0.05463724583387375
epoch :  2043  loss :  0.0545874647796154
epoch :  2044  loss :  0.05454229563474655
epoch :  2045  loss :  0.05449158698320389
epoch :  2046  loss :  0.05444863438606262
epoch :  2047  loss :  0.05439681559801102
epoch :  2048  loss :  0.054350823163986206
epoch :  2049  loss :  0.054305028170347214
epoch :  2050  loss :  0.054255761206150055
epoch :  2051  loss :  0.05421070381999016
epoch :  2052  loss :  0.0541611984372139
epoch :  2053  loss :  0.05411679670214653
epoch :  2054  loss :  0.05406716465950012
epoch :  2055  loss :  0.05402389168739319
epoch :  2056  loss :  0.053972989320755005
epoch :  2057  loss :  0.053929902613162994
epoch :  2058  loss :  0.053880125284194946
epoch :  2059  loss :  0.053834639489650726
epoch :  2060  loss :  0.05378810316324234
epoch :  2061  loss :  0.05373981595039

## torch.nn.module을 사용해서 많은 간단한 레이어를 복잡한 뉴럴 네트워크로 만들 수 있습니다.

In [12]:
class custom_class(nn.Module):
    def __init__(self, n_in, n_h, n_out):
        super(custom_class, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(n_in, n_h),
            nn.ReLU(),
            nn.Linear(n_h, n_out),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

In [13]:
custom_nn = custom_class(n_in, n_h, n_out)

In [14]:
loss_func = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [15]:
for i in range(25):
    y_pred = custom_nn(x)
    loss = loss_func(y_pred, y)

    print("epoch : ", (i + 1), " loss : ", loss.item())
    loss.backward() # 역전파 적용

    optimizer.step() # 모든 파라미터 최신화

    optimizer.zero_grad()

epoch :  1  loss :  0.27303898334503174
epoch :  2  loss :  0.27303898334503174
epoch :  3  loss :  0.27303898334503174
epoch :  4  loss :  0.27303898334503174
epoch :  5  loss :  0.27303898334503174
epoch :  6  loss :  0.27303898334503174
epoch :  7  loss :  0.27303898334503174
epoch :  8  loss :  0.27303898334503174
epoch :  9  loss :  0.27303898334503174
epoch :  10  loss :  0.27303898334503174
epoch :  11  loss :  0.27303898334503174
epoch :  12  loss :  0.27303898334503174
epoch :  13  loss :  0.27303898334503174
epoch :  14  loss :  0.27303898334503174
epoch :  15  loss :  0.27303898334503174
epoch :  16  loss :  0.27303898334503174
epoch :  17  loss :  0.27303898334503174
epoch :  18  loss :  0.27303898334503174
epoch :  19  loss :  0.27303898334503174
epoch :  20  loss :  0.27303898334503174
epoch :  21  loss :  0.27303898334503174
epoch :  22  loss :  0.27303898334503174
epoch :  23  loss :  0.27303898334503174
epoch :  24  loss :  0.27303898334503174
epoch :  25  loss :  0.27

In [16]:
import torch
import torch.optim as optim
import torch.nn as nn

# torch.nn : neural network를 만드는데 꼭 필요한 모듈

In [17]:
import numpy as np
import matplotlib.pyplot as plt

In [18]:
class EgLayer(nn.Module):
    def __init__(self, param):
        super().__init__()
        self.param = param

    def forward(self, x):
        return x * self.param

myOb= EgLayer(8)

output = myOb(torch.Tensor([1, 2, 3]))
print(output)

tensor([ 8., 16., 24.])


In [19]:
n_in, n_h, n_out = 6, 4, 1

In [21]:
x = torch.randn((1, n_in))
y = torch.randn((1, n_out))
x, y

(tensor([[ 1.3514,  1.8417,  0.4698, -0.0643,  2.0279,  1.4978]]),
 tensor([[-1.6934]]))

In [22]:
b1 = torch.randn((1, n_h))
b2 = torch.randn((1, n_out))
b1, b2

(tensor([[-2.0724, -0.4351,  0.8066, -1.9947]]), tensor([[-0.5564]]))

In [26]:
w1 = torch.randn(n_in, n_h)
w2 = torch.randn(n_h, n_out)
w1, w2

(tensor([[-1.7803,  0.2866, -0.5959,  0.0068],
         [-1.0222,  0.4391,  0.4681, -1.5267],
         [ 0.0290,  1.2527,  0.1160, -0.3396],
         [ 0.6189,  0.1403,  2.0113,  0.8271],
         [ 0.7983,  0.5444,  0.7498,  0.0356],
         [ 1.6316, -0.2317, -0.4515,  0.5038]]),
 tensor([[-0.0023],
         [ 0.7440],
         [-0.4143],
         [-0.5438]]))

In [23]:
def sigmoid_activation(z):
    return 1 / (1 + torch.exp(-z))

In [27]:
z1 = torch.mm(x, w1) + b1
a1 = sigmoid_activation(z1)

In [28]:
z2 = torch.mm(a1, w2) + b2
output = sigmoid_activation(z2)

In [29]:
loss = y - output

In [31]:
def sigmoid_delta(x):
    return x * (1 - x)

In [32]:
delta_out = sigmoid_delta(output)
delta_h = sigmoid_delta(a1)

In [33]:
d_outp = loss * delta_out
loss_h = torch.mm(d_outp, w2.t())
d_hidn = loss_h * delta_h