## pytorch_study.ipynb

In [1]:
import torch
import numpy as np

In [2]:
list1 = ([1, 2], [3, 4])

In [3]:
type(list1)

tuple

In [4]:
example_tensor = torch.tensor(list1)

In [6]:
example_tensor

tensor([[1, 2],
        [3, 4]])

In [7]:
type(example_tensor)

torch.Tensor

In [8]:
list2 = [1, 2, 3, 4, 5]

In [9]:
type(list2)

list

In [10]:
example_tensor = torch.tensor(list2)

In [11]:
example_tensor

tensor([1, 2, 3, 4, 5])

In [12]:
type(example_tensor)

torch.Tensor

In [13]:
np_tensor = torch.tensor(np.array([1, 2, 3, 4, 5, 6]))

In [14]:
np_tensor

tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)

In [15]:
type(np_tensor)

torch.Tensor

In [17]:
example_tensor = torch.tensor(1)

In [18]:
example_tensor

tensor(1)

In [19]:
type(example_tensor)

torch.Tensor

In [20]:
empty_tensor = torch.tensor([])

In [21]:
empty_tensor

tensor([])

In [22]:
tensor_float = torch.tensor([3, 4, 5], dtype = torch.float32)

In [23]:
tensor_float

tensor([3., 4., 5.])

In [27]:
tensor_int = torch.tensor([3, 4, 5], dtype = torch.int32)

In [28]:
tensor_int

tensor([3, 4, 5], dtype=torch.int32)

In [29]:
tensor_float.dtype, tensor_int.dtype

(torch.float32, torch.int32)

In [30]:
x = torch.ones(3, 2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [31]:
x_zero = torch.zeros(3, 3)
print(x_zero)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [54]:
x_zero.dtype

torch.float32

In [41]:
# 0 ~ 1 사이의 임의이 값
torch.rand(4, 2)

tensor([[0.6522, 0.1945],
        [0.7157, 0.5015],
        [0.8373, 0.9055],
        [0.6714, 0.6012]])

In [44]:
y = torch.arange(10)
y

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
torch.arange(5, 10)

tensor([5, 6, 7, 8, 9])

In [46]:
torch.arange(5 ,50, 5)

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [49]:
torch.linspace(0, 50, 10)

tensor([ 0.0000,  5.5556, 11.1111, 16.6667, 22.2222, 27.7778, 33.3333, 38.8889,
        44.4444, 50.0000])

In [52]:
torch.empty(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [53]:
torch.empty(3, 3).dtype

torch.float32

In [56]:
# identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [61]:
torch.full((3, 4), 0.)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [63]:
torch.full((3, 4), 0.).dtype

torch.float32

In [69]:
new_tensor = torch.arange(9)
new_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
new_tensor.shape

torch.Size([9])

In [72]:
new_tensor.view(3, 3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [73]:
new_tensor.view(1, 9)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [74]:
new_tensor.view(9, 1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

In [82]:
new_tensor = torch.arange(2, 18, 2)
new_tensor

tensor([ 2,  4,  6,  8, 10, 12, 14, 16])

In [83]:
new_tensor.view(2, 4)

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16]])

In [84]:
new_tensor.reshape(2, 4)

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16]])

### tensor.view : contiguous tensor에만 적용이 가능, 메모리에 적용되지 않음
### tensor.reshape : 어떤 tensor에도 가능, 메모리에 적용함

In [86]:
x = torch.arange(8).reshape(4, 2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [87]:
x[2, 1]

tensor(5)

In [88]:
x[2, 1].item()

5

In [89]:
type(x[2, 1].item())

int